INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 74, in check_user_photo
    user_photo = context.bot.getFile()
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
TypeError: get_file() missing 1 required positional argument: 'file_id'
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 53, in send_cat_picture
    context.bot.send_photo(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 699, in send_photo
    return self._message(  # type: ignore[return-value]
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 354, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Button_data_invalid
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 56, in send_cat_picture
    context.bot.send_photo(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 699, in send_photo
    return self._message(  # type: ignore[return-value]
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 354, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Button_data_invalid
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 56, in send_cat_picture
    context.bot.send_photo(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 699, in send_photo
    return self._message(  # type: ignore[return-value]
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 354, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Button_data_invalid
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 56, in send_cat_picture
    context.bot.send_photo(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 699, in send_photo
    return self._message(  # type: ignore[return-value]
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 354, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Button_data_invalid
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 57, in send_cat_picture
    context.bot.send_photo(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 699, in send_photo
    return self._message(  # type: ignore[return-value]
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 354, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Button_data_invalid
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 57, in send_cat_picture
    context.bot.send_photo(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 699, in send_photo
    return self._message(  # type: ignore[return-value]
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 354, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Button_data_invalid
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 57, in send_cat_picture
    context.bot.send_photo(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 699, in send_photo
    return self._message(  # type: ignore[return-value]
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 354, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Button_data_invalid
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 74, in check_user_photo
    user_photo = context.bot.getFile(update.message.photo[-1].file_unique_id)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 2307, in get_file
    result = self._post('getFile', data, timeout=timeout, api_kwargs=api_kwargs)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Invalid file_id
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 80, in check_user_photo
    new_filename = os.path.join("images", f"cat_{len(cat_photo_list) + 1 + datetime.now().strftime('%d.%m.%Y_%H:%M:S')}.jpg")
TypeError: unsupported operand type(s) for +: 'int' and 'str'
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "d:\PYPROJ\tr_bot\env\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "d:\PYPROJ\tr_bot\handlers.py", line 81, in check_user_photo
    os.rename(file_name, new_filename)
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'downloads\\AgACAgIAAxkBAAICNGHpxRppb9rZf1kepBWmnHvhbZVcAAIyuzEb8aNRS-n9AgfnE5o_AQADAgADbQADIwQ.jpg' -> 'images\\cat_1020.01.2022_23:25:S.jpg'
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Added job "send_upds" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
